version: "3"
services:

  api:
    build:
      context: ../src/api
    networks:
      - backend
    ports:
      - "8080:8080"
    volumes:
      - ../src/api/cpu_loader:/tmp/api/cpu_loader
    env_file: .env
    environment:
      - CACHE_TYPE=simple
      - PYTHONPATH=/tmp/api/
    command: bash -c "cd /tmp/api/cpu_loader && /usr/local/bin/gunicorn -w 4 -b :8080 app:app"


networks:
  backend:
