version: "3"
services:

  api:
    build:
      context: ../src/api
    networks:
      - backend
    ports:
      - "8080:8080"
    volumes:
      - ../src/api/cpu_loader:/tmp/api/cpu_loader
    env_file: .env
    command: bash -c "cd /tmp/api/cpu_loader && /usr/local/bin/gunicorn -w 1 -b :8080 app:app"

networks:
  backend:
